# This is a basic workflow to help you get started with Actions

name: Building

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, zhi-github-action]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: noetic
      - name: Create Workspace
        run: "mkdir -p ros_ws/src"  
      - uses: actions/checkout@v2
        with:
          path: ros_ws/src/tbd_podi
      - uses: actions/checkout@v2
        with:
          repository: cmu-tbd/tbd_screen_face
          path: ros_ws/src/tbd_screen_face
      - name: Install ROS dependencies
        run: |
          rosdep update
          cd ros_ws
          rosdep install --from-paths src --ignore-src --rosdistro noetic
      - name: Catkin Build
        run: |
          source /opt/ros/noetic/setup.bash
          cd ros_ws
          catkin_make_isolated

      
